dist: bionic
language: python

install:
# Install libvrt & KVM (see https://github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev ruby-bundler bsdtar libz-dev libxml2-dev

script:
- git clone https://github.com/vagrant-libvirt/vagrant-libvirt/
- cd vagrant-libvirt
- git revert 608037c15c099161ba3354d5083c4dcb99405fba --no-edit
- sudo bundle install
- sudo bundle --binstubs /tmp/exec
- sudo VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 /tmp/exec/vagrant plugin install vagrant-reload
- cd ..
- sudo ./vagrant-libvirt-test-cycle.sh
